/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import BUS.*;
import DAO.*;
import DTO.*;
import java.awt.Color;
import java.awt.HeadlessException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tranconghung
 */
public class TaikhoanNhanvienJFrame extends javax.swing.JFrame {
    private DefaultTableModel jtbtaikhoannhanvienModel;
    private  int idTaikhoanNV;
    private TaikhoanNhanvien taikhoanNhanvienUpdate = new TaikhoanNhanvien();
    private TaikhoanNhanvien taikhoanNhanvienDelete = new TaikhoanNhanvien();
    /**
     * Creates new form TaikhoanNhanvienJFrame
     */
    public TaikhoanNhanvienJFrame() {
        initComponents();
        initTable();
        LoadTable();
    }
    public void initTable(){
        jtbtaikhoannhanvienModel = new DefaultTableModel();
        jtbtaikhoannhanvienModel.setColumnIdentifiers(new String[]{"Tên đăng nhập","Mã nhân viên","Mật khẩu","Trạng thái","Ảnh đại diện"});
        jtbTaikhoanNhanvien.setModel(jtbtaikhoannhanvienModel);
    }
    public void LoadTable(){
        try {
            TaiKhoanNhanVienBUS taiKhoanNhanVienBUS = new TaiKhoanNhanVienBUS();
            List<TaikhoanNhanvien> list = taiKhoanNhanVienBUS.LoadTaiKhoanNhanVien(WIDTH);
            jtbtaikhoannhanvienModel.setRowCount(0);
            for(TaikhoanNhanvien tk : list){
                jtbtaikhoannhanvienModel.addRow(new Object[]{
                    tk.getTenDangNhap(),tk.getID(),tk.getMatKhau(),tk.getTrangThai(),tk.getAnhDaiDien()
                });
            }
            jtbtaikhoannhanvienModel.fireTableDataChanged();
//            idTaikhoanNV = list.size() + 1;
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private boolean checkIdNhanvien() throws HeadlessException{
        StringBuilder bd = new StringBuilder();
        if(jtfManv.getText().equals("")){
            bd.append("Mã nhân viên không được để tróng");
        }
        if(bd.length() > 0){
            JOptionPane.showMessageDialog(this, bd, "Cảnh báo", JOptionPane.ERROR_MESSAGE);
            jtfManv.setBackground(Color.red);
            return true;
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbTaikhoanNhanvien = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfUsername = new javax.swing.JTextField();
        jtfManv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfPassword = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfTrangthai = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfAnhdaidien = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnShowNhanVien = new javax.swing.JButton();
        jtfTimkiem = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnTimkiem = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtbTaikhoanNhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbTaikhoanNhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbTaikhoanNhanvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbTaikhoanNhanvien);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin tài khoản nhân viên"));

        jLabel1.setText("Tên đăng nhập");

        jLabel2.setText("Mã nhân viên");

        jLabel3.setText("Mật khẩu");

        jLabel4.setText("Trạng thái");

        jLabel5.setText("Ảnh đại diện");

        btnShowNhanVien.setText("...");
        btnShowNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowNhanVienActionPerformed(evt);
            }
        });

        jLabel6.setText("Tìm kiếm");

        btnTimkiem.setText("Tìm kiếm");
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });

        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setText("Sửa");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(219, 219, 219)
                                .addComponent(btnShowNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jtfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfManv, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfAnhdaidien, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(jtfTrangthai))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTimkiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSave)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)
                        .addGap(43, 43, 43))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfManv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnShowNhanVien)
                    .addComponent(jtfTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(btnTimkiem))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfAnhdaidien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimkiemActionPerformed

    private void btnShowNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowNhanVienActionPerformed
        TableNhanVien tbNhanVien = new TableNhanVien();
        try {
            tbNhanVien.list();
        } catch (Exception e) {
             Logger.getLogger(TableNhanVien.class.getName()).log(Level.SEVERE, null, e);
        }
        tbNhanVien.setVisible(true);
    }//GEN-LAST:event_btnShowNhanVienActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(checkIdNhanvien()) return;
        try {
            TaikhoanNhanvien taikhoanNhanvien = new TaikhoanNhanvien();
            taikhoanNhanvien.setTenDangNhap(jtfUsername.getText());
            taikhoanNhanvien.setID(Integer.parseInt(jtfManv.getText()));
            taikhoanNhanvien.setMatKhau(jtfPassword.getText());
            taikhoanNhanvien.setTrangThai(Integer.parseInt(jtfTrangthai.getText()));
            taikhoanNhanvien.setAnhDaiDien(jtfAnhdaidien.getText());
            TaiKhoanNhanVienBUS taiKhoanNhanVienBUS = new TaiKhoanNhanVienBUS();
            if(taiKhoanNhanVienBUS.insertTaiKhoanNV(taikhoanNhanvien) > 0 ){
                JOptionPane.showMessageDialog(this, "Thêm tài khoản thành công");
                jtfUsername.setText("");
                jtfManv.setText("");
                jtfPassword.setText("");
                jtfTrangthai.setText("");
                jtfAnhdaidien.setText("");
                LoadTable();
            }
            else{
                JOptionPane.showMessageDialog(this,"Thêm tài khoản thất bại" , "Cảnh báo", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,"Tên đặng nhập đã tồn tại" , "Cảnh báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jtbTaikhoanNhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbTaikhoanNhanvienMouseClicked
        try {
            int row = jtbTaikhoanNhanvien.getSelectedRow();
            if(row >= 0){
                String Username =  jtbTaikhoanNhanvien.getValueAt(row, 0).toString();
                int ID = (Integer)jtbTaikhoanNhanvien.getValueAt(row, 1);
                TaiKhoanNhanVienBUS taiKhoanNhanVienBUS = new TaiKhoanNhanVienBUS();
                TaikhoanNhanvien taikhoanNhanvien  = taiKhoanNhanVienBUS.getTaikhoanNhanvien(Username);
                taikhoanNhanvienUpdate = taiKhoanNhanVienBUS.getIDTaikhoanNhanvien(ID);
                taikhoanNhanvienDelete = taiKhoanNhanVienBUS.getTaikhoanNhanvien(Username);
                if(taikhoanNhanvien != null){
                    jtfUsername.setText(taikhoanNhanvien.getTenDangNhap());
                    jtfManv.setText(String.valueOf(taikhoanNhanvien.getID()));
                    jtfPassword.setText(taikhoanNhanvien.getMatKhau());
                    jtfTrangthai.setText(String.valueOf(taikhoanNhanvien.getTrangThai()));
                    jtfAnhdaidien.setText(taikhoanNhanvien.getAnhDaiDien());
                    
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtbTaikhoanNhanvienMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            TaikhoanNhanvien tknv = new TaikhoanNhanvien();
            tknv = this.taikhoanNhanvienUpdate;
            tknv.setTenDangNhap(jtfUsername.getText());
            tknv.setMatKhau(jtfPassword.getText());
            tknv.setTrangThai(Integer.parseInt(jtfTrangthai.getText()));
            tknv.setAnhDaiDien(jtfAnhdaidien.getText());
            tknv.setID(Integer.parseInt(jtfManv.getText()));
            
            if(JOptionPane.showConfirmDialog(this, "Bạn có muốn Update không?", "Hỏi"
            , JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.NO_OPTION){
            return;
            }
            TaiKhoanNhanVienBUS tknvbus = new TaiKhoanNhanVienBUS();
            if(tknvbus.updateTaiKhoanNV(tknv) > 0 ){
                JOptionPane.showMessageDialog(null, "Update thành công");
                jtfUsername.setText("");
                jtfPassword.setText("");
                jtfTrangthai.setText("");
                jtfAnhdaidien.setText("");
//                jtfManv.setText("");
                LoadTable();
            }
            else{
                JOptionPane.showMessageDialog(null, "Update thất bại");
            }
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "abcUpdate thất bại");
             Logger.getLogger(NhanVienJFrame.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            if(JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không?", "Hỏi"
            , JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.NO_OPTION){
            return;
            }
            TaiKhoanNhanVienBUS tknvbus = new TaiKhoanNhanVienBUS();
            if(tknvbus.deleteTaiKhoanNV(taikhoanNhanvienDelete)){
                JOptionPane.showMessageDialog(null, "Xóa thành công");
                LoadTable();
            }
            else{
                JOptionPane.showMessageDialog(null, "Xóa thất bại");
            }
        } catch (Exception e) {
            Logger.getLogger(NhanVienJFrame.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaikhoanNhanvienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaikhoanNhanvienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaikhoanNhanvienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaikhoanNhanvienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaikhoanNhanvienJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnShowNhanVien;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbTaikhoanNhanvien;
    private javax.swing.JTextField jtfAnhdaidien;
    private javax.swing.JTextField jtfManv;
    private javax.swing.JTextField jtfPassword;
    private javax.swing.JTextField jtfTimkiem;
    private javax.swing.JTextField jtfTrangthai;
    private javax.swing.JTextField jtfUsername;
    // End of variables declaration//GEN-END:variables
}
